Tas to do

4.1.   Problem _1    Array creation


 1. Initialize an empty array with size 2X2.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
x = np.zeros([2,2], dtype = int)
print(x);


[[0 0]
 [0 0]]


2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np
x = np.ones([4,2], dtype = int)
print(x);

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np

shape = (3, 4)
fill_value = 7
dtype = int

filled_array = np.full(shape, fill_value, dtype=dtype)

print("Array filled with value:")
print(filled_array)


Array filled with value:
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np


original_array = np.array([[1, 2, 3], [4, 5, 6]])

zeros_array = np.zeros_like(original_array)

print("Original array:")
print(original_array)
print("\nZeros array:")
print(zeros_array)


Original array:
[[1 2 3]
 [4 5 6]]

Zeros array:
[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np
original_array = np.array([[5,6,7],[8,9,2]])
ones_array = np.ones_like(original_array)
print("Original array:")
print(original_array)
print("\nOnes array:")
print(ones_array)


Original array:
[[5 6 7]
 [8 9 2]]

Ones array:
[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
original_array = np.array(new_list)
print("Original list:")
print(new_list)
print("\nNumpy array:")
print( numpy_array)

Original list:
[1, 2, 3, 4]

Numpy array:
[1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

array = np.arange(10, 50)

print("Array with values from 10 to 49:")
print(array)


Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
import numpy as np

array = np.arange(9)


matrix = array.reshape(3, 3)

print("3x3 Matrix with values from 0 to 8:")
print(matrix)


3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np

identity_matrix = np.eye(3)

print("3x3 Identity Matrix:")
print(identity_matrix)


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np


random_array = np.random.random(30)

mean_value = random_array.mean()

print("Random Array:")
print(random_array)
print("\nMean of the Array:")
print(mean_value)


Random Array:
[0.15208584 0.26668232 0.71787    0.43713699 0.75254786 0.45188989
 0.22833184 0.7807389  0.58191355 0.48689309 0.7461222  0.03723109
 0.86833038 0.67939889 0.19799411 0.44483336 0.21788483 0.43297951
 0.64594085 0.13735472 0.26380912 0.67775992 0.21326572 0.01377172
 0.42787125 0.93247775 0.35176221 0.07137595 0.72026597 0.11630608]

Mean of the Array:
0.4350941968848215


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np


random_array = np.random.random((10, 10))

min_value = random_array.min()
max_value = random_array.max()

print("10x10 Array with Random Values:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


10x10 Array with Random Values:
[[0.93371008 0.55716051 0.51342657 0.68345928 0.46329718 0.49177247
  0.90410897 0.76067238 0.3163791  0.96018298]
 [0.25287885 0.13738822 0.14299225 0.60997759 0.47840725 0.10512721
  0.96231079 0.03315396 0.01678321 0.83045585]
 [0.49639181 0.51951108 0.30991669 0.67391307 0.84844639 0.11902398
  0.24537769 0.944504   0.61574952 0.06548694]
 [0.14826371 0.2067076  0.48547246 0.37523499 0.33517457 0.73305656
  0.68783451 0.25745594 0.29690983 0.75542416]
 [0.71428228 0.56963719 0.31374776 0.90387933 0.41782015 0.29774008
  0.20311129 0.56191565 0.49641452 0.60282795]
 [0.66438064 0.91291729 0.14848448 0.59832752 0.16969745 0.49026439
  0.29398491 0.32056619 0.38357162 0.87597549]
 [0.4484232  0.05121408 0.83398432 0.22257176 0.45510796 0.73417659
  0.98399259 0.73598492 0.37276463 0.72239087]
 [0.80186845 0.83138805 0.49403173 0.17009442 0.82106046 0.49004748
  0.51144446 0.15680391 0.02346784 0.1038327 ]
 [0.99914911 0.43078019 0.96683454 0.79568058 0.

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np

zero_array = np.zeros(10)

zero_array[4] = 1

print("Modified Array:")
print(zero_array)


Modified Array:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])

reversed_arr = arr[::-1]

print("Original Array:")
print(arr)
print("\nReversed Array:")
print(reversed_arr)


Original Array:
[1 2 0 0 4 0]

Reversed Array:
[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np


array = np.ones((5, 5), dtype=int)


array[1:-1, 1:-1] = 0

print("2D Array with 1s on the border and 0s inside:")
print(array)


2D Array with 1s on the border and 0s inside:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)


checkerboard[::2, ::2] = 1
checkerboard[1::2, 1::2] = 1

print("8x8 Checkerboard Pattern:")
print(checkerboard)


8x8 Checkerboard Pattern:
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Problem - 3: Array Operations:

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

1. Add the two array.

In [ ]:
import numpy as np


array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])


sum_array = array1 + array2

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nSum of the Arrays:")
print(sum_array)


Array 1:
[1 2 3]

Array 2:
[4 5 6]

Sum of the Arrays:
[5 7 9]


2. Subtract the two array.

In [ ]:
import numpy as np


array1 = np.array([5, 10, 15])
array2 = np.array([2, 3, 4])


difference_array = array1 - array2

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nDifference of the Arrays:")
print(difference_array)


Array 1:
[ 5 10 15]

Array 2:
[2 3 4]

Difference of the Arrays:
[ 3  7 11]


3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np


array = np.array([1, 2, 3, 4])


multiplied_array = array * 3

print("Original Array:")
print(array)

print("\nArray after multiplying by 3:")
print(multiplied_array)


Original Array:
[1 2 3 4]

Array after multiplying by 3:
[ 3  6  9 12]


4. Find the square of each element of the array.

In [ ]:
import numpy as np


array = np.array([1, 2, 3, 4])


squared_array = array ** 2

print("Original Array:")
print(array)

print("\nSquared Array:")
print(squared_array)


Original Array:
[1 2 3 4]

Squared Array:
[ 1  4  9 16]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np


v = np.array([1, 2])
w = np.array([3, 4])
x = np.array([5, 6])
y = np.array([7, 8])


dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)


print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:", dot_x_v)
print("Dot product of x and y:", dot_x_y)


Dot product of v and w: 11
Dot product of x and v: 17
Dot product of x and y: 83


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np

v = np.array([1, 2])
w = np.array([3, 4])
x = np.array([5, 6])
y = np.array([7, 8])


concat_x_y = np.concatenate((x, y))


concat_v_w = np.vstack((v, w))


print("Concatenation of x and y along row:")
print(concat_x_y)

print("\nConcatenation of v and w along column:")
print(concat_v_w)


Concatenation of x and y along row:
[5 6 7 8]

Concatenation of v and w along column:
[[1 2]
 [3 4]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np


v = np.array([1, 2])
x = np.array([5, 6])

try:
    concat_x_v = np.concatenate((x, v))
    print("Concatenation of x and v:")
    print(concat_x_v)
except ValueError as e:
    print(f"Error: {e}")


Concatenation of x and v:
[5 6 1 2]


No error in this case: The arrays x and v are both one-dimensional arrays of the same size, so they can be concatenated along the first axis (horizontally).
Shape of x and v: Both x = [5, 6] and v = [1, 2] have the shape (2,), meaning they both have 2 elements, so they can be concatenated directly into a single array [5, 6, 1, 2].


Problem - 4: Matrix Operations:

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT.

In [ ]:
import numpy as np


A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)


AB = np.dot(A, B)
BA = np.dot(B, A)


AB_T = np.transpose(AB)
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))

print("1. A * A^-1 (Identity Matrix):\n", identity_matrix)
print("\n2. AB:\n", AB)
print("   BA:\n", BA)
print("   AB == BA?", np.array_equal(AB, BA))

print("\n3. (AB)^T:\n", AB_T)
print("   B^T * A^T:\n", B_T_A_T)
print("   (AB)^T == B^T * A^T?", np.array_equal(AB_T, B_T_A_T))


1. A * A^-1 (Identity Matrix):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB:
 [[23 13]
 [51 29]]
   BA:
 [[36 44]
 [13 16]]
   AB == BA? False

3. (AB)^T:
 [[23 51]
 [13 29]]
   B^T * A^T:
 [[23 51]
 [13 29]]
   (AB)^T == B^T * A^T? True


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
import numpy as np


A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])


B = np.array([-1, -3, 9])


A_inv = np.linalg.inv(A)


X = np.dot(A_inv, B)


print("Solution (x, y, z):")
print(X)


Solution (x, y, z):
[ 2.  1. -2.]


Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

From the above question using np.linalg.inv(is explained in details).



*  np.linalg.inv(A): This function computes the inverse of matrix
A
A. If
A
A is invertible, it returns
A
−
1
A
−1
 .

*  np.dot(A_inv, B): This performs matrix multiplication of the inverse of
A
A and
B
B to compute the solution
X
X, which contains the values of
x
x,
y
y, and
z
z.



4.2 Experiment: How Fast is Numpy?

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import time
import numpy as np


size = 1000000

list1 = [i for i in range(size)]
list2 = [i for i in range(size, 2*size)]


start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()

print("Time taken for element-wise addition using Python Lists: {:.6f} seconds".format(end_time - start_time))


array1 = np.arange(size)
array2 = np.arange(size, 2*size)

start_time = time.time()
result_array = array1 + array2
end_time = time.time()

print("Time taken for element-wise addition using NumPy Arrays: {:.6f} seconds".format(end_time - start_time))


Time taken for element-wise addition using Python Lists: 0.155476 seconds
Time taken for element-wise addition using NumPy Arrays: 0.004266 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import time
import numpy as np


size = 1000000


list1 = [i for i in range(size)]
list2 = [i for i in range(size, 2*size)]


start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()

print("Time taken for element-wise multiplication using Python Lists: {:.6f} seconds".format(end_time - start_time))


array1 = np.arange(size)
array2 = np.arange(size, 2*size)

start_time = time.time()
result_array = array1 * array2
end_time = time.time()

print("Time taken for element-wise multiplication using NumPy Arrays: {:.6f} seconds".format(end_time - start_time))


Time taken for element-wise multiplication using Python Lists: 0.150232 seconds
Time taken for element-wise multiplication using NumPy Arrays: 0.004488 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import time
import numpy as np


size = 1000000


list1 = [i for i in range(size)]
list2 = [i for i in range(size, 2*size)]


start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()

print("Time taken for dot product using Python Lists: {:.6f} seconds".format(end_time - start_time))


array1 = np.arange(size)
array2 = np.arange(size, 2*size)

start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()

print("Time taken for dot product using NumPy Arrays: {:.6f} seconds".format(end_time - start_time))


Time taken for dot product using Python Lists: 0.171826 seconds
Time taken for dot product using NumPy Arrays: 0.001424 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import time
import numpy as np


size = 1000

matrix1 = [[i + j for j in range(size)] for i in range(size)]
matrix2 = [[i - j for j in range(size)] for i in range(size)]

start_time = time.time()

result_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size)) for j in range(size)] for i in range(size)]

end_time = time.time()
print("Time taken for matrix multiplication using Python Lists: {:.6f} seconds".format(end_time - start_time))

array1 = np.random.randint(1, 10, (size, size))
array2 = np.random.randint(1, 10, (size, size))

start_time = time.time()


result_array = np.dot(array1, array2)

end_time = time.time()
print("Time taken for matrix multiplication using NumPy Arrays: {:.6f} seconds".format(end_time - start_time))


Time taken for matrix multiplication using Python Lists: 253.501995 seconds
Time taken for matrix multiplication using NumPy Arrays: 1.292179 seconds
